apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgB1G5oWmtdIiz7aC6PTNEZjLCr7/zarZ64A1nVxODksqemMJiU6qV7iVlHJ08nIZRmUvCkXGiH3Vde85la1ObLo9E1zAdtCGEXNU+8TwE0l/HkIgyYcJYxLrpujXqeEpkg7J0X4W29I1nalcXaKushLn0ZfykxFTliI4HGXsLEvyeXUpjmWSemYOIQ6+HR1iqTS3UGo3pdSSRHMm+tsSTIMZ0hRwn2sPgqAapu+rvqGxI4rZHPgJJL/5IdKrDeEZtbIFf0eq8m2nQNODTero7IkvvMNL2BuzO5aAIRd9gOQ1+vIGgg1kytiDvwajwUMzKkxwtL1Yy0EmDxFg+YYYcmZZmrdCWogZulU86x47FoCsg0LjPrP7CgE69M1cyPpBj4qrPtgLayVmtqfJQjuaKz8D83XXQOI9nYIVNP9ks5KD5ln236ZGt8Afi+L2e2802ZpIXHnUOvwsncB35JJ5RfIwB2tiX5l50dmeikSCJ6qHLC50LhUIlWruzZFGSpIHo777T0IQ/X9SkImsr4fEAv6kdIQKVqlSAlvfA8nUKT00xPR0YKGyDKIOqWUMKFAZm0c73qw5gLldmAf2wlBLi14EUd97+VZm/Kugvkao7e+uwg3gosYBvqYyzMt1V+ximFGbGQzyHRP3tDc3dcRtO8y/6rReHi1drHqJbP+9J5KTdFB2k/7vkbtU3o4vU4EVPuoe0t0gGK6jT2vnkxvpkqwHzVKGeXOUcDe
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

